
// CONSTANTS TO ADD MOVIE

export const ADD_MOVIE_LOADING = 'ADD_MOVIE_LOADING';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAIL = 'ADD_MOVIE_FAIL'
export const ADD_MOVIE_RESET = 'ADD_MOVIE_RESET'


// CONSTANTS TO GET ALL MOVIES

export const GET_MOVIES_LOADING = 'GET_MOVIES_LOADING';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';
export const GET_MOVIES_RESET = 'GET_MOVIES_RESET';


// CONSTANTS TO EDIT MOVIE

export const EDIT_MOVIE_LOADING = 'EDIT_MOVIE_LOADING';
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS'
export const EDIT_MOVIE_FAIL = 'EDIT_MOVIE_FAIL'
export const EDIT_MOVIE_RESET = 'EDIT_MOVIE_RESET'


// CONSTANTS TO GET SINGLE MOVIE

export const GET_MOVIE_LOADING = 'GET_MOVIE_LOADING';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';
export const GET_MOVIE_RESET = 'GET_MOVIE_RESET';


// CONSTANTS TO DELETE MOVIE

export const DELETE_MOVIE_LOADING = 'DELETE_MOVIE_LOADING';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAIL = 'DELETE_MOVIE_FAIL';
export const DELETE_MOVIE_RESET = 'DELETE_MOVIE_RESET';