
// CONSTANTS TO CREATE REVIEW

export const CREATE_REVIEW_LOADING = 'CREATE_REVIEW_LOADING';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';
export const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET';



// CONSTANTS TO GET REVIEWS BY MOVIE

export const GET_REVIEWS_MOVIE_LOADING = 'GET_REVIEWS_MOVIE_LOADING'
export const GET_REVIEWS_MOVIE_SUCCESS = 'GET_REVIEWS_MOVIE_SUCCESS'
export const GET_REVIEWS_MOVIE_FAIL = 'GET_REVIEWS_MOVIE_FAIL'
export const GET_REVIEWS_MOVIE_RESET = 'GET_REVIEWS_MOVIE_RESET'


// CONSTANTS TO GET REVIEWS BY USER

export const GET_REVIEWS_USER_LOADING = 'GET_REVIEWS_USER_LOADING'
export const GET_REVIEWS_USER_SUCCESS = 'GET_REVIEWS_USER_SUCCESS'
export const GET_REVIEWS_USER_FAIL = 'GET_REVIEWS_USER_FAIL'
export const GET_REVIEWS_USER_RESET = 'GET_REVIEWS_USER_RESET'


// CONSTANTS TO GET SINGLE REVIEW

export const GET_REVIEW_LOADING = 'GET_REVIEW_LOADING';
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const GET_REVIEW_FAIL = 'GET_REVIEW_FAIL';
export const GET_REVIEW_RESET = 'GET_REVIEW_RESET';


// CONSTANTS TO DELETE REVIEW

export const DELETE_REVIEW_LOADING = 'DELETE_REVIEW_LOADING';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET';


// CONSTANTS TO UPDATE REVIEW

export const UPDATE_REVIEW_LOADING = 'UPDATE_REVIEW_LOADING';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL';
export const UPDATE_REVIEW_RESET = 'UPDATE_REVIEW_RESET';