
// CONSTANTS TO REGISTER USER

export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";



// CONSTANTS TO LOGIN USER

export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";


// CONSTANTS TO SET WATCHED LIST OF USER

export const USER_WATCHLIST_LOADING = "USER_WATCHLIST_LOADING";
export const USER_WATCHLIST_SUCCESS = "USER_WATCHLIST_SUCCESS";
export const USER_WATCHLIST_FAIL = "USER_WATCHLIST_FAIL";
export const USER_WATCHLIST_RESET = "USER_WATCHLIST_RESET";


// CONSTANTS TO DELETE USER

export const USER_DELETE_LOADING = "USER_DELETE_LOADING";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";


// CONSTANTS TO UPDATE USER

export const USER_UPDATE_LOADING = "USER_UPDATE_LOADING";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";


// CONSTANTS TO GET WATCHED LIST OF USER

export const USER_GET_WATCHLIST_LOADING = "USER_GET_WATCHLIST_LOADING";
export const USER_GET_WATCHLIST_SUCCESS = "USER_GET_WATCHLIST_SUCCESS";
export const USER_GET_WATCHLIST_FAIL = "USER_GET_WATCHLIST_FAIL";
export const USER_GET_WATCHLIST_RESET = "USER_GET_WATCHLIST_RESET";


// CONSTANTS GET USERS LIST FOR ADMIN

export const USERS_LIST_LOADING = "USERS_LIST_LOADING";
export const USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS";
export const USERS_LIST_FAIL = "USERS_LIST_FAIL";
export const USERS_LIST_RESET = "USERS_LIST_RESET";

